# Generated by Django 5.2.11 on 2026-03-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packer_address',
            field=models.TextField(blank=True),
        ),
    ]
