# Generated by Django 5.2.11 on 2026-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_country_of_origin_product_generic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='section',
            field=models.CharField(choices=[('specs', 'Specifications'), ('manufacturer', 'Manufacturer Info')], default='specs', max_length=30),
        ),
    ]
