# Generated by Django 5.2.4 on 2026-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sale_saleadvertisement_vendorsalenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleadvertisement',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Stock available for this sale'),
        ),
        migrations.AddField(
            model_name='saleadvertisement',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Your sale price for this product', max_digits=10),
            preserve_default=False,
        ),
    ]
