# Generated by Django 5.2.4 on 2026-03-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_bundle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP / original price before discount', max_digits=10, null=True),
        ),
    ]
