# Generated by Django 5.2.11 on 2026-02-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
