# Generated by Django 5.2.11 on 2026-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guestlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlocation',
            name='source',
            field=models.CharField(choices=[('gps', 'GPS / Browser'), ('ip', 'IP Geolocation'), ('manual', 'Manual Entry')], default='gps', max_length=10),
        ),
        migrations.AlterField(
            model_name='guestlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='guestlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
