# Generated by Django 5.2.4 on 2026-03-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_smart_search_query'),
        ('recommender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_purchase_count', models.PositiveIntegerField(default=1)),
                ('score', models.FloatField(default=0.0, help_text='Normalised co-purchase score')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='algorithm',
            field=models.CharField(default='als', help_text='als | mf | hybrid | content', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='action_type',
            field=models.CharField(choices=[('search', 'Search'), ('view', 'View'), ('click', 'Click'), ('cart', 'Add To Cart'), ('purchase', 'Purchase')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='product_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='product_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'action_type'], name='recommender_user_id_e0fa45_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['product_id', 'action_type'], name='recommender_product_8af5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'score'], name='recommender_user_id_f49178_idx'),
        ),
        migrations.AddField(
            model_name='frequentlyboughttogether',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_main', to='products.product'),
        ),
        migrations.AddField(
            model_name='frequentlyboughttogether',
            name='related_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_as_companion', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='frequentlyboughttogether',
            index=models.Index(fields=['product', 'score'], name='recommender_product_7810ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frequentlyboughttogether',
            unique_together={('product', 'related_product')},
        ),
    ]
